-- Standard SQL example
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

---

DECLARE
NAME VARCHAR2(100);
BEGIN
FOR R IN (SELECT * FROM EMPLOYEES WHERE HIRE_DATE = SYSDATE - 4000)
LOOP
	NAME := R.FIRST_NAME || ' ' || R.LAST_NAME;
  DBMS_OUTPUT.PUT_LINE('HAPPY ANNIVERSARY ' || NAME);
END LOOP;
END;

---

CREATE OR REPLACE FUNCTION IS_NUMBER(STRING IN VARCHAR2) RETURN VARCHAR2 IS
VALUE NUMBER;
BEGIN
VALUE := TO_NUMBER(STRING);
RETURN 'YES';
EXCEPTION
WHEN OTHERS THEN RETURN 'NO';
END;
/

---

BEGIN
DBMS_OUTPUT.PUT_LINE(IS_NUMBER('83'));
END;

---

CREATE OR REPLACE TRIGGER T6 
BEFORE DELETE ON EMPLOYEES
FOR EACH ROW
DECLARE
BEGIN
DBMS_OUTPUT.PUT_LINE('HELLO WORLD6');
END;
/

---

DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = 183;

---

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 183;

---

ROLLBACK;

---

CREATE OR REPLACE TRIGGER INVALID_NAME BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
DECLARE
e_invalid_input EXCEPTION;
NEW_NAME VARCHAR2(100);
BEGIN 
NEW_NAME := :NEW.FIRST_NAME;
IF NOT REGEXP_LIKE(NEW_NAME, '^[A-Za-z]+$') THEN RAISE e_invalid_input;
END IF;
EXCEPTION
WHEN e_invalid_input THEN RAISE_APPLICATION_ERROR(-20001, 'FIRST NAME MUST CONATIN ONLY ALPHABETIC CHARACTERS');
END;
/

---

INSERT INTO EMPLOYEES (
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER,
  HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID
) VALUES (
  183, 'Steven83', 'King', 'STVNKNG', '515.123.4567',
  TO_DATE('2003-06-17', 'YYYY-MM-DD'), 'AD_PRES', 27600,
  NULL, NULL, 90
);

---

CREATE TABLE LOW_SALARY_EMPLOYEES(
EMPLOYEE_ID NUMBER,
SALARY NUMBER
);

---

CREATE OR REPLACE TRIGGER LOW_SALARY_EMPLOYEE_INPUT BEFORE INSERT ON EMPLOYEES FOR EACH ROW
DECLARE
BEGIN
IF (:NEW.SALARY <1000) THEN INSERT INTO LOW_SALARY_EMPLOYEES VALUES (:NEW.EMPLOYEE_ID, :NEW.SALARY);
END IF;
END;
/

---

INSERT INTO EMPLOYEES (
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER,
  HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID
) VALUES (
  10833, 'Steven', 'King', 'STVNKNGSS', '515.123.4567',
  TO_DATE('2003-06-17', 'YYYY-MM-DD'), 'AD_PRES', 600,
  NULL, NULL, 90
);
/

---

SELECT * FROM LOW_SALARY_EMPLOYEES;

