-- 5.1

SELECT E.LAST_NAME, E.SALARY, J.JOB_TITLE
FROM EMPLOYEES E
JOIN JOBS J
ON (E.JOB_ID = J.JOB_ID);
 
 
SELECT D.DEPARTMENT_NAME, C.COUNTRY_NAME
FROM DEPARTMENTS D
JOIN LOCATIONS L
ON (D.LOCATION_ID = L.LOCATION_ID)
JOIN COUNTRIES C
ON (L.COUNTRY_ID = C.COUNTRY_ID);


SELECT C.COUNTRY_NAME, COUNT(DEPARTMENT_ID)
FROM COUNTRIES C
JOIN LOCATIONS L
ON (C.COUNTRY_ID = L.COUNTRY_ID)
JOIN DEPARTMENTS D
ON (D.LOCATION_ID = L.LOCATION_ID)
GROUP BY C.COUNTRY_NAME;


SELECT E.EMPLOYEE_ID, COUNT(J.EMPLOYEE_ID)
FROM EMPLOYEES E 
LEFT OUTER JOIN JOB_HISTORY J 
ON (E.EMPLOYEE_ID = J.EMPLOYEE_ID)
GROUP BY E.EMPLOYEE_ID;


SELECT J.JOB_TITLE, COUNT(E.EMPLOYEE_ID)
FROM JOBS J 
JOIN EMPLOYEES E 
ON (J.JOB_ID = E.JOB_ID)
GROUP BY J.JOB_TITLE;


SELECT D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID)
FROM DEPARTMENTS D 
JOIN EMPLOYEES E 
ON (D.DEPARTMENT_ID = E.DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME;


SELECT D.DEPARTMENT_NAME, J.JOB_TITLE, COUNT(E.EMPLOYEE_ID)
FROM EMPLOYEES E
JOIN JOBS J 
ON (E.JOB_ID = J.JOB_ID)
JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME, J.JOB_TITLE;


SELECT E.LAST_NAME, COUNT(DISTINCT E2.EMPLOYEE_ID) BEFORE, COUNT(DISTINCT E3.EMPLOYEE_ID) AS AFTER
FROM EMPLOYEES E 
LEFT OUTER JOIN EMPLOYEES E2 
ON (E.HIRE_DATE > E2.HIRE_DATE)
LEFT OUTER JOIN EMPLOYEES E3
ON (E.HIRE_DATE < E3.HIRE_DATE)
GROUP BY E.LAST_NAME;


SELECT E.LAST_NAME, COUNT(E2.EMPLOYEE_ID) AS GT
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES E2
ON (E.SALARY>E2.SALARY)
GROUP BY E.LAST_NAME
HAVING COUNT(E2.EMPLOYEE_ID)>=3;


SELECT E.LAST_NAME,COUNT(DISTINCT E2.SALARY)
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES E2
ON (E.SALARY <= E2.SALARY)
GROUP BY E.LAST_NAME,E.EMPLOYEE_ID
ORDER BY COUNT(E2.EMPLOYEE_ID);


SELECT E.LAST_NAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES E2
ON (E.SALARY <= E2.SALARY)
GROUP BY E.EMPLOYEE_ID, E.LAST_NAME
HAVING COUNT(DISTINCT E2.SALARY)<=3;