-- 6.2

SELECT E.LAST_NAME, E.SALARY
FROM EMPLOYEES E
WHERE 3<=
(
SELECT COUNT(E2.EMPLOYEE_ID) FROM EMPLOYEES E2 WHERE 
E2.SALARY > E.SALARY);


SELECT D.DEPARTMENT_NAME FROM DEPARTMENTS D
WHERE (SELECT AVG(SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = D.DEPARTMENT_ID) >
ALL (SELECT MIN(SALARY) FROM EMPLOYEES E WHERE E.DEPARTMENT_ID <> D.DEPARTMENT_ID GROUP BY E.DEPARTMENT_ID
);


SELECT D.DEPARTMENT_NAME FROM DEPARTMENTS D
WHERE (SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE DEPARTMENT_ID = D.DEPARTMENT_ID GROUP BY DEPARTMENT_ID) > ALL
(
SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE DEPARTMENT_ID <> D.DEPARTMENT_ID GROUP BY DEPARTMENT_ID
);


SELECT E.LAST_NAME FROM EMPLOYEES E WHERE 1<
(SELECT COUNT(*) FROM JOB_HISTORY WHERE EMPLOYEE_ID = E.EMPLOYEE_ID GROUP BY EMPLOYEE_ID
);


SELECT E.LAST_NAME FROM EMPLOYEES E WHERE EXISTS
(SELECT 1 FROM JOB_HISTORY WHERE EMPLOYEE_ID = E.EMPLOYEE_ID
);


SELECT E.LAST_NAME, D.MINSAL, D.MAXSAL 
FROM EMPLOYEES E, (SELECT DEPARTMENT_ID,
MIN(SALARY) MINSAL, MAX(SALARY) MAXSAL FROM EMPLOYEES  GROUP BY DEPARTMENT_ID
) D WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;


SELECT J.JOB_TITLE, E.LAST_NAME 
FROM JOBS J, (
SELECT X.JOB_ID, X.LAST_NAME FROM EMPLOYEES X
WHERE X.SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = X.DEPARTMENT_ID GROUP BY DEPARTMENT_ID)
) E WHERE J.JOB_ID = E.JOB_ID;
























