SELECT * FROM EMPLOYEES E1
WHERE 3 <=
(
SELECT COUNT(*) FROM EMPLOYEES E2 WHERE E2.SALARY < E1.SALARY 
);

SELECT
DEPARTMENT_NAME
FROM
DEPARTMENTS D
WHERE
0 < (SELECT COUNT(*) FROM EMPLOYEES E WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID AND JOB_ID = 'IT_PROG');
 
 
  
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS D 
WHERE  EXISTS 
( 
SELECT * 
FROM EMPLOYEES E 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND JOB_ID = 'IT_PROG' 
);

SELECT * FROM EMPLOYEES E
WHERE NOT EXISTS
(
SELECT FIRST_NAME FROM EMPLOYEES E2 WHERE E2.SALARY>E.SALARY
);


SELECT E.LAST_NAME, E.SALARY, (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID) DEPARTMENT 
FROM EMPLOYEES E
WHERE NOT EXISTS(
SELECT * FROM EMPLOYEES E2
WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
AND E2.SALARY > E.SALARY);


SELECT LAST_NAME, SALARY, (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D  
WHERE D.DEPARTMENT_ID = E1.DEPARTMENT_ID) 
DEPARTMENT 
FROM EMPLOYEES E1 
WHERE  NOT EXISTS 
( 
SELECT * 
FROM EMPLOYEES E2 
WHERE E2.DEPARTMENT_ID = E1.DEPARTMENT_ID AND 
E2.SALARY > E1.SALARY 
); 

SELECT E.LAST_NAME, E.SALARY, D.MINSAL, D.MAXSAL,D.DEPT
FROM EMPLOYEES E,
( 
SELECT DEPARTMENT_ID DEPT, MIN(SALARY) MINSAL, MAX(SALARY) MAXSAL 
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID 
) D 
WHERE (E.DEPARTMENT_ID = D.DEPT)  
ORDER BY E.SALARY ; 



